### ISSUE TITLE
Creating new Signup/Signin Flows

### ISSUE THREAD

**Issue by huxley** [idlesign/django-sitegate#17]
Is there a recommended way to create a new signup/signin flows?

My use case is doing case-insensitive matches on the username followed by the email address, where the username can be different from the email address.

**Comment by huxley** [comment]
Having re-read the documentation, I now see that it's covered under the Custom Signup Flows and Combining Signin Flows. So I can just inherit from one of the flows and customize it to my needs. Cool.

Linking the sections of the docs just for anyone like myself that didn't realize how flexible the system actually is: 

*  http://django-sitegate.readthedocs.org/en/latest/signup_custom.html#custom-signup-flows-examples
*  http://django-sitegate.readthedocs.org/en/latest/signin_custom.html#combining-sign-in-flows

**Comment by idlesign** [comment]
Sorry. I've answered this one by e-mail, and seems that GitHub won't accept it.
The answer was:

For this very case the most natural way would be adding, say, 'username_case_sensitive' bool attribute to existing base *-flow class. That should trigger alternative implementations of login or user creation. So that required behaviour could be chosen in sitegate decorators.

If implemented this feature is a clear candidate for pull request.

**Comment by huxley** [comment]
Great, I'll look over the code more closely and make a pull request if I think I find a good implementation. Thanks!
